services:
  learning-session-service:
    image: learningsessionservice:1.0.0-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod