services:
  service-registry:
    image: service-registry:1.0.0-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: prod