services:
  curricular-service:
    image: curricularservice:1.0.0-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod